### ISSUE TITLE
Error creating screenshot on python client.py

### ISSUE THREAD

**Issue by amitaibu** [cmck/pybrowserstack-screenshots#4]
`python client.py --config ie7.json --auth my-auth:my-token`

Error message:

```
using config ie7.json
Traceback (most recent call last):
  File "client.py", line 249, in <module>
    main(sys.argv[1:])
  File "client.py", line 240, in main
    generate_resp_json = s.generate_screenshots()
  File "/Library/WebServer/Documents/pybrowserstack-screenshots/browserstack_screenshots/__init__.py", line 86, in generate_screenshots
    resp = self._process_response(resp)
  File "/Library/WebServer/Documents/pybrowserstack-screenshots/browserstack_screenshots/__init__.py", line 55, in _process_response
    raise ScreenshotNotAllowedError("Screenshot not allowed")
browserstack_screenshots.ScreenshotNotAllowedError: Screenshot not allowed
```

**Comment by amitaibu** [comment]
Problem seems to be that the Search API wasn't enabled - seems there's no error handling for that case

**Comment by quinn-madson** [comment]
I am running into the same issue. How did you solve this? Do you mean Search API or Screenshot API?

**Comment by amitaibu** [comment]
> How did you solve this?

I'm using [webdrivercss](https://github.com/webdriverio/webdrivercss)

**Comment by cmck** [comment]
Your account must have Screenshots API access enabled, which last time I checked is not available on the free trial. I will improve the error reporting for this case
